import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const importedExtractor = await import(path.join(root, 'ChromeExtension/transcript-extractor.js'));
const extractor = importedExtractor.default ?? importedExtractor;

function element(text) {
  return { innerText: text, textContent: text };
}
function segment(timestamp, caption) {
  return {
    querySelector(selector) {
      if (selector.includes('timestamp')) return element(timestamp);
      if (selector.includes('text')) return element(caption);
      return null;
    }
  };
}

test('parses YouTube minute and hour timestamps', () => {
  assert.equal(extractor.parseTimestamp('12:45'), 765_000);
  assert.equal(extractor.parseTimestamp('1:02:15'), 3_735_000);
  assert.equal(extractor.parseTimestamp('not-a-time'), null);
});

test('extracts ordered cues and preserves explicit caption line breaks', () => {
  const cues = extractor.extractCues([
    segment('12:45', 'A synthetic first line.'),
    segment('12:51', 'A second line.\nBreak preserved.')
  ]);
  assert.deepEqual(cues, [
    { startTimeMilliseconds: 765_000, text: 'A synthetic first line.' },
    { startTimeMilliseconds: 771_000, text: 'A second line.\nBreak preserved.' }
  ]);
});

test('rejects empty and malformed transcript segments', () => {
  assert.deepEqual(extractor.extractCues([segment('0:01', '  \n  ')]), []);
  assert.deepEqual(extractor.extractCues([segment('bad', 'Synthetic text')]), []);
});

test('builds a local capture message only for English YouTube transcript pages', () => {
  const result = extractor.buildCaptureMessage({
    requestID: 'e6b7b1e7-cc6d-4d34-9ab9-c8ec20dd85ce',
    videoID: '5fJl_ZX91l0',
    title: 'Fictional test video',
    languageName: 'English',
    isAutoGenerated: null
  }, [{ startTimeMilliseconds: 1_000, text: 'Invented sample caption.' }]);
  assert.equal(result.type, 'captiongrab.transcript');
  assert.equal(result.videoURL, 'https://www.youtube.com/watch?v=5fJl_ZX91l0');
  assert.equal(result.cues[0].text, 'Invented sample caption.');
  assert.equal(result.isAutoGenerated, null);
  assert.throws(() => extractor.buildCaptureMessage({
    requestID: 'e6b7b1e7-cc6d-4d34-9ab9-c8ec20dd85ce',
    videoID: '5fJl_ZX91l0',
    title: 'Fictional test video',
    languageName: 'French'
  }, [{ startTimeMilliseconds: 1_000, text: 'Faux.' }]), /English/);
});

test('extension manifest requests only the YouTube page and native-messaging permission', async () => {
  const manifest = JSON.parse(await readFile(path.join(root, 'ChromeExtension/manifest.json'), 'utf8'));
  assert.equal(manifest.manifest_version, 3);
  assert.deepEqual(manifest.permissions, ['nativeMessaging']);
  assert.deepEqual(manifest.host_permissions, ['https://www.youtube.com/*']);
  assert.ok(!('cookies' in manifest.permissions));
  assert.ok(!('cookies' in (manifest.optional_permissions ?? [])));
  const publicKey = Buffer.from(manifest.key, 'base64');
  const digest = createHash('sha256').update(publicKey).digest().subarray(0, 16);
  const id = digest.toString('hex').replace(/[0-9a-f]/g, digit => String.fromCharCode(97 + Number.parseInt(digit, 16)));
  assert.equal(id, 'kajphiodjnkmgeidbcndikaaegghiffi');
});
