import AppKit
import CaptionGrabCore
import Combine
import Foundation
import UniformTypeIdentifiers

@MainActor
final class AppModel: ObservableObject {
    @Published var inputURL = ""
    @Published private(set) var transcript: TranscriptData?
    @Published private(set) var isLoading = false
    @Published private(set) var errorMessage: String?
    @Published private(set) var noticeMessage: String?
    @Published private(set) var chromeDebugLog: String?
    @Published private(set) var didCopyChromeDebugLog = false
    @Published private(set) var history: [RecentVideo]
    @Published private(set) var preferredFormat: ExportFormat

    private let client = YouTubeTranscriptClient()
    private let historyStore = RecentHistoryStore()
    private let defaults = UserDefaults.standard
    private let bookmarkKey = "CaptionGrab.lastSaveFolderBookmark"
    private let formatKey = "CaptionGrab.lastExportFormat"

    init() {
        ChromeCompanionConstants.clearLegacyChromeFolderBookmark(from: UserDefaults.standard)
        history = historyStore.load()
        preferredFormat = ExportFormat(rawValue: UserDefaults.standard.string(forKey: "CaptionGrab.lastExportFormat") ?? "") ?? .markdown
    }

    var shouldShowAppTranslocationRecovery: Bool {
        errorMessage?.contains("CaptionGrab.AppTranslocation") == true
    }

    var captionTypeDescription: String? {
        guard let transcript else { return nil }
        switch transcript.isAutoGenerated {
        case true: return "Auto-generated English captions"
        case false: return "Creator-made English captions"
        case nil: return "English captions"
        }
    }

    func fetchTranscript() async {
        errorMessage = nil
        noticeMessage = nil
        chromeDebugLog = nil
        didCopyChromeDebugLog = false
        transcript = nil
        isLoading = true
        defer { isLoading = false }

        do {
            let link = try YouTubeLink.parse(inputURL)
            let result: TranscriptData
            do {
                result = try await client.fetch(link: link)
            } catch let directError as CaptionGrabError {
                switch directError {
                case .noEnglishCaptions, .videoUnavailable, .requestBlocked, .youtubeChanged:
                    result = try await ChromeTranscriptBridge.fetch(link: link) { [weak self] log in
                        if let log { self?.chromeDebugLog = log }
                    }
                default:
                    throw directError
                }
            }
            transcript = result
            inputURL = link.canonicalURL.absoluteString
            historyStore.record(RecentVideo(videoID: link.videoID, title: result.videoTitle, videoURL: link.canonicalURL))
            history = historyStore.load()
        } catch {
            errorMessage = error.localizedDescription
        }
    }

    func openApplicationsFolder() {
        NSWorkspace.shared.open(URL(fileURLWithPath: "/Applications", isDirectory: true))
    }

    func quitCaptionGrab() {
        NSApp.terminate(nil)
    }

    func setupChromeExtension() {
        errorMessage = nil
        noticeMessage = nil
        do {
            let extensionURL = try ChromeCompanionSetup.install()
            NSWorkspace.shared.activateFileViewerSelecting([extensionURL])
            if let chromeURL = URL(string: "chrome://extensions"),
               let chromeApp = NSWorkspace.shared.urlForApplication(withBundleIdentifier: "com.google.Chrome") {
                NSWorkspace.shared.open([chromeURL], withApplicationAt: chromeApp, configuration: NSWorkspace.OpenConfiguration(), completionHandler: nil)
            }
            let registrationPath = ChromeCompanionConstants.chromeNativeMessagingDirectory()
                .appendingPathComponent(ChromeCompanionConstants.nativeHostManifestFileName).path
            let inboxPath = ChromeCompanionConstants.transcriptInboxDirectory().path
            let installedBundleURL = extensionURL
                .deletingLastPathComponent()
                .deletingLastPathComponent()
                .deletingLastPathComponent()
            let hostPath = ChromeCompanionConstants.nativeHostExecutable(bundleURL: installedBundleURL).path
            noticeMessage = "Chrome helper installed from \(installedBundleURL.path). Load the extension folder shown in Finder at chrome://extensions.\nNative Messaging helper: \(hostPath)\nNative Messaging manifest: \(registrationPath)\nTranscript storage: \(inboxPath)"
        } catch {
            errorMessage = error.localizedDescription
        }
    }

    func loadRecent(_ video: RecentVideo) {
        inputURL = video.videoURL.absoluteString
        Task { await fetchTranscript() }
    }

    func clearHistory() {
        historyStore.clear()
        history = []
    }

    func copyDebugLog() {
        guard let chromeDebugLog else { return }
        NSPasteboard.general.clearContents()
        NSPasteboard.general.setString(chromeDebugLog, forType: .string)
        didCopyChromeDebugLog = true
        noticeMessage = "Copied the Chrome debug log. Paste it into your reply."
    }

    func copyAll() {
        guard let transcript else { return }
        NSPasteboard.general.clearContents()
        NSPasteboard.general.setString(TranscriptFormatter.markdown(for: transcript), forType: .string)
        noticeMessage = "Copied the formatted transcript."
        errorMessage = nil
    }

    func save(_ format: ExportFormat) {
        guard let transcript else { return }
        preferredFormat = format
        defaults.set(format.rawValue, forKey: formatKey)
        errorMessage = nil
        noticeMessage = nil

        let panel = NSSavePanel()
        panel.allowedContentTypes = [format.contentType]
        panel.canCreateDirectories = true
        panel.isExtensionHidden = false
        panel.nameFieldStringValue = ExportFilename.safeBaseName(transcript.videoTitle) + format.fileExtension
        panel.prompt = "Save"

        let rememberedFolder = resolveSaveFolder()
        let folderAccess = rememberedFolder?.startAccessingSecurityScopedResource() ?? false
        if let rememberedFolder { panel.directoryURL = rememberedFolder }
        let response = panel.runModal()
        if folderAccess { rememberedFolder?.stopAccessingSecurityScopedResource() }
        guard response == .OK, let destination = panel.url else { return }

        let destinationAccess = destination.startAccessingSecurityScopedResource()
        defer {
            if destinationAccess { destination.stopAccessingSecurityScopedResource() }
        }

        do {
            switch format {
            case .markdown:
                try Data(TranscriptFormatter.markdown(for: transcript).utf8).write(to: destination, options: .atomic)
            case .word:
                try DocxExporter.makeDOCX(for: transcript).write(to: destination, options: .atomic)
            }
            rememberSaveFolder(panel.directoryURL ?? destination.deletingLastPathComponent())
            noticeMessage = "Saved \(destination.lastPathComponent)."
        } catch {
            errorMessage = CaptionGrabError.exportFailed.localizedDescription
        }
    }

    private func resolveSaveFolder() -> URL? {
        guard let data = defaults.data(forKey: bookmarkKey) else { return nil }
        var stale = false
        guard let folder = try? URL(
            resolvingBookmarkData: data,
            options: [.withSecurityScope, .withoutUI],
            relativeTo: nil,
            bookmarkDataIsStale: &stale
        ), !stale else { return nil }
        return folder
    }

    private func rememberSaveFolder(_ folder: URL) {
        guard let bookmark = try? folder.bookmarkData(
            options: [.withSecurityScope],
            includingResourceValuesForKeys: nil,
            relativeTo: nil
        ) else { return }
        defaults.set(bookmark, forKey: bookmarkKey)
    }
}

enum ExportFormat: String, CaseIterable, Identifiable {
    case markdown
    case word

    var id: String { rawValue }
    var fileExtension: String { self == .markdown ? ".md" : ".docx" }
    var contentType: UTType {
        switch self {
        case .markdown: UTType(filenameExtension: "md") ?? .plainText
        case .word: UTType(filenameExtension: "docx") ?? .data
        }
    }
    var label: String { self == .markdown ? "Markdown (.md)" : "Word document (.docx)" }
}
