import XCTest
@testable import CaptionGrabCore

final class CaptionTrackTests: XCTestCase {
    private func track(_ code: String, generated: Bool, name: String = "English") -> CaptionTrack {
        CaptionTrack(
            languageCode: code,
            languageName: name,
            isAutoGenerated: generated,
            captionURL: URL(string: "https://www.youtube.com/api/timedtext?v=fixture")!
        )
    }

    func testCreatorMadeEnglishWinsEvenWhenGeneratedTrackAppearsFirst() {
        let selected = CaptionTrackSelector.englishTrack(from: [
            track("en", generated: true),
            track("en-US", generated: false)
        ])
        XCTAssertEqual(selected?.languageCode, "en-US")
        XCTAssertEqual(selected?.isAutoGenerated, false)
    }

    func testUsesEnglishGeneratedTrackWhenNoCreatorTrackExists() {
        let selected = CaptionTrackSelector.englishTrack(from: [
            track("fr", generated: false, name: "French"),
            track("en", generated: true)
        ])
        XCTAssertEqual(selected?.languageCode, "en")
        XCTAssertEqual(selected?.isAutoGenerated, true)
    }

    func testDoesNotSelectTranslatedNonEnglishTrack() {
        let selected = CaptionTrackSelector.englishTrack(from: [
            track("fr", generated: false, name: "English (auto-translated)")
        ])
        XCTAssertNil(selected)
    }

    func testReturnsNoTrackWhenThereAreNoCaptionTracks() {
        XCTAssertNil(CaptionTrackSelector.englishTrack(from: []))
    }
}
