import XCTest
@testable import CaptionGrabCore

final class ChromeTranscriptMessageTests: XCTestCase {
    private let requestID = "e6b7b1e7-cc6d-4d34-9ab9-c8ec20dd85ce"
    private let videoID = "5fJl_ZX91l0"
    private var videoURL: URL { URL(string: "https://www.youtube.com/watch?v=5fJl_ZX91l0")! }

    func testDecodesSyntheticChromeTranscriptAndPreservesCueBreaks() throws {
        let fixture = #"{"type":"captiongrab.transcript","requestID":"e6b7b1e7-cc6d-4d34-9ab9-c8ec20dd85ce","videoID":"5fJl_ZX91l0","videoURL":"https://www.youtube.com/watch?v=5fJl_ZX91l0","title":"Fictional test video","captionLanguage":"English","isAutoGenerated":null,"cues":[{"startTimeMilliseconds":765000,"text":"Made-up first cue."},{"startTimeMilliseconds":771000,"text":"Second invented line.\nBreak preserved."}]}"#
        let message = try JSONDecoder().decode(ChromeTranscriptMessage.self, from: Data(fixture.utf8))
        let transcript = try message.makeTranscript(
            expectedRequestID: requestID,
            expectedVideoID: videoID,
            canonicalURL: videoURL
        )
        XCTAssertEqual(transcript.videoTitle, "Fictional test video")
        XCTAssertNil(transcript.isAutoGenerated)
        XCTAssertEqual(transcript.cues.last?.text, "Second invented line.\nBreak preserved.")
    }

    func testRejectsTranscriptForAnotherVideoOrRequest() throws {
        let fixture = #"{"type":"captiongrab.transcript","requestID":"e6b7b1e7-cc6d-4d34-9ab9-c8ec20dd85ce","videoID":"5fJl_ZX91l0","videoURL":"https://www.youtube.com/watch?v=5fJl_ZX91l0","title":"Fictional test video","captionLanguage":"English","isAutoGenerated":false,"cues":[{"startTimeMilliseconds":1000,"text":"Invented cue."}]}"#
        let message = try JSONDecoder().decode(ChromeTranscriptMessage.self, from: Data(fixture.utf8))
        XCTAssertThrowsError(try message.makeTranscript(
            expectedRequestID: requestID,
            expectedVideoID: "A1b2C3d4E5F",
            canonicalURL: URL(string: "https://www.youtube.com/watch?v=A1b2C3d4E5F")!
        ))
        XCTAssertThrowsError(try message.makeTranscript(
            expectedRequestID: "c3bf6c2a-c3c4-4cb6-bd4c-fd58fc10727a",
            expectedVideoID: videoID,
            canonicalURL: videoURL
        ))
    }

    func testReturnsExplicitErrorFromSyntheticBrowserResponse() throws {
        let fixture = #"{"type":"captiongrab.error","requestID":"e6b7b1e7-cc6d-4d34-9ab9-c8ec20dd85ce","videoID":"5fJl_ZX91l0","error":"YouTube did not show an English transcript."}"#
        let message = try JSONDecoder().decode(ChromeTranscriptMessage.self, from: Data(fixture.utf8))
        XCTAssertThrowsError(try message.makeTranscript(
            expectedRequestID: requestID,
            expectedVideoID: videoID,
            canonicalURL: videoURL
        )) { error in
            XCTAssertEqual(error as? ChromeTranscriptMessageError, .transcriptUnavailable("YouTube did not show an English transcript."))
        }
    }
}
