import XCTest
@testable import CaptionGrabCore

final class ChromeTranscriptMessageTests: XCTestCase {
    private let requestID = "e6b7b1e7-cc6d-4d34-9ab9-c8ec20dd85ce"
    private let videoID = "5fJl_ZX91l0"
    private var videoURL: URL { URL(string: "https://www.youtube.com/watch?v=5fJl_ZX91l0")! }

    func testDecodesSyntheticChromeTranscriptAndPreservesCueBreaks() throws {
        let fixture = #"{"type":"captiongrab.transcript","requestID":"e6b7b1e7-cc6d-4d34-9ab9-c8ec20dd85ce","videoID":"5fJl_ZX91l0","videoURL":"https://www.youtube.com/watch?v=5fJl_ZX91l0","title":"Fictional test video","captionLanguage":"English","isAutoGenerated":null,"cues":[{"startTimeMilliseconds":765000,"text":"Made-up first cue."},{"startTimeMilliseconds":771000,"text":"Second invented line.\nBreak preserved."}]}"#
        let message = try JSONDecoder().decode(ChromeTranscriptMessage.self, from: Data(fixture.utf8))
        let transcript = try message.makeTranscript(
            expectedRequestID: requestID,
            expectedVideoID: videoID,
            canonicalURL: videoURL
        )
        XCTAssertEqual(transcript.videoTitle, "Fictional test video")
        XCTAssertNil(transcript.isAutoGenerated)
        XCTAssertEqual(transcript.cues.last?.text, "Second invented line.\nBreak preserved.")
    }

    func testAcceptsTranscriptAsDisplayedWithoutClaimingAnEnglishTrack() throws {
        let fixture = #"{"type":"captiongrab.transcript","requestID":"e6b7b1e7-cc6d-4d34-9ab9-c8ec20dd85ce","videoID":"5fJl_ZX91l0","videoURL":"https://www.youtube.com/watch?v=5fJl_ZX91l0","title":"Fictional test video","captionLanguage":"as-displayed","isAutoGenerated":null,"cues":[{"startTimeMilliseconds":1000,"text":"An invented caption."}]}"#
        let message = try JSONDecoder().decode(ChromeTranscriptMessage.self, from: Data(fixture.utf8))
        let transcript = try message.makeTranscript(expectedRequestID: requestID, expectedVideoID: videoID, canonicalURL: videoURL)
        XCTAssertNil(transcript.isAutoGenerated)
        XCTAssertEqual(transcript.cues.first?.text, "An invented caption.")
    }

    func testPreservesAutoGeneratedFallbackMarkerForTheAppWarning() throws {
        let fixture = #"{"type":"captiongrab.transcript","requestID":"e6b7b1e7-cc6d-4d34-9ab9-c8ec20dd85ce","videoID":"5fJl_ZX91l0","videoURL":"https://www.youtube.com/watch?v=5fJl_ZX91l0","title":"Fictional test video","captionLanguage":"English","isAutoGenerated":true,"cues":[{"startTimeMilliseconds":1000,"text":"Invented auto-generated cue."}]}"#
        let message = try JSONDecoder().decode(ChromeTranscriptMessage.self, from: Data(fixture.utf8))
        let transcript = try message.makeTranscript(
            expectedRequestID: requestID,
            expectedVideoID: videoID,
            canonicalURL: videoURL
        )
        XCTAssertEqual(transcript.isAutoGenerated, true)
    }

    func testRejectsTranscriptForAnotherVideoOrRequest() throws {
        let fixture = #"{"type":"captiongrab.transcript","requestID":"e6b7b1e7-cc6d-4d34-9ab9-c8ec20dd85ce","videoID":"5fJl_ZX91l0","videoURL":"https://www.youtube.com/watch?v=5fJl_ZX91l0","title":"Fictional test video","captionLanguage":"English","isAutoGenerated":false,"cues":[{"startTimeMilliseconds":1000,"text":"Invented cue."}]}"#
        let message = try JSONDecoder().decode(ChromeTranscriptMessage.self, from: Data(fixture.utf8))
        XCTAssertThrowsError(try message.makeTranscript(
            expectedRequestID: requestID,
            expectedVideoID: "A1b2C3d4E5F",
            canonicalURL: URL(string: "https://www.youtube.com/watch?v=A1b2C3d4E5F")!
        ))
        XCTAssertThrowsError(try message.makeTranscript(
            expectedRequestID: "c3bf6c2a-c3c4-4cb6-bd4c-fd58fc10727a",
            expectedVideoID: videoID,
            canonicalURL: videoURL
        ))
    }

    func testManualPanelInstructionsArePassedThroughToTheApp() throws {
        let instructions = "CaptionGrab could not find YouTube’s transcript button automatically. In the Chrome video tab, expand “...more” in the description if shown, scroll down in the expanded description, and click the “Show transcript” button. If the “In this video” panel opens on “Chapters,” click its “Transcript” tab. Wait for transcript lines to appear, then try Get transcript again."
        let fixture = #"{"type":"captiongrab.error","requestID":"e6b7b1e7-cc6d-4d34-9ab9-c8ec20dd85ce","videoID":"5fJl_ZX91l0","error":"CaptionGrab could not find YouTube’s transcript button automatically. In the Chrome video tab, expand “...more” in the description if shown, scroll down in the expanded description, and click the “Show transcript” button. If the “In this video” panel opens on “Chapters,” click its “Transcript” tab. Wait for transcript lines to appear, then try Get transcript again."}"#
        let message = try JSONDecoder().decode(ChromeTranscriptMessage.self, from: Data(fixture.utf8))
        XCTAssertThrowsError(try message.makeTranscript(
            expectedRequestID: requestID,
            expectedVideoID: videoID,
            canonicalURL: videoURL
        )) { error in
            XCTAssertEqual(error as? ChromeTranscriptMessageError, .transcriptUnavailable(instructions))
        }
    }

    func testIncludesStepByStepChromeAutomationProgressInTheAppError() throws {
        let fixture = #"{"type":"captiongrab.error","requestID":"e6b7b1e7-cc6d-4d34-9ab9-c8ec20dd85ce","videoID":"5fJl_ZX91l0","error":"YouTube did not show the transcript panel after CaptionGrab clicked its button.","progress":{"descriptionExpanded":true,"transcriptSectionFound":true,"transcriptButtonFound":true,"transcriptButtonClicked":true,"panelOpened":false,"transcriptTabSelected":false,"transcriptLinesLoaded":false}}"#
        let message = try JSONDecoder().decode(ChromeTranscriptMessage.self, from: Data(fixture.utf8))
        let expected = """
        YouTube did not show the transcript panel after CaptionGrab clicked its button.

        Chrome automation progress:
        - Description expanded: yes
        - Transcript section found: yes
        - Show transcript button found: yes
        - Show transcript button clicked: yes
        - Transcript panel opened: no
        - Transcript tab selected: no
        - Transcript lines loaded: no
        """
        XCTAssertThrowsError(try message.makeTranscript(
            expectedRequestID: requestID,
            expectedVideoID: videoID,
            canonicalURL: videoURL
        )) { error in
            XCTAssertEqual(error as? ChromeTranscriptMessageError, .transcriptUnavailable(expected))
        }
    }

    func testDecodesExtensionDebugLogForCopyInTheApp() throws {
        let log = "[+0ms] automation started {\"readyState\":\"complete\"}\n[+300ms] clicked Show transcript control"
        let object: [String: Any] = [
            "type": "captiongrab.error",
            "requestID": requestID,
            "videoID": videoID,
            "error": "Show transcript was not clicked.",
            "debugLog": log
        ]
        let data = try JSONSerialization.data(withJSONObject: object)
        let message = try JSONDecoder().decode(ChromeTranscriptMessage.self, from: data)
        XCTAssertEqual(message.debugLog, log)
        XCTAssertThrowsError(try message.makeTranscript(
            expectedRequestID: requestID,
            expectedVideoID: videoID,
            canonicalURL: videoURL
        ))
    }

    func testRejectsOversizedExtensionDebugLog() throws {
        let object: [String: Any] = [
            "type": "captiongrab.error",
            "requestID": requestID,
            "videoID": videoID,
            "error": "Synthetic failure.",
            "debugLog": String(repeating: "x", count: 30_001)
        ]
        let data = try JSONSerialization.data(withJSONObject: object)
        let message = try JSONDecoder().decode(ChromeTranscriptMessage.self, from: data)
        XCTAssertThrowsError(try message.makeTranscript(
            expectedRequestID: requestID,
            expectedVideoID: videoID,
            canonicalURL: videoURL
        )) { error in
            XCTAssertEqual(error as? ChromeTranscriptMessageError, .invalidMessage("Chrome returned an oversized diagnostic log."))
        }
    }

    func testReturnsExplicitErrorFromSyntheticBrowserResponse() throws {
        let fixture = #"{"type":"captiongrab.error","requestID":"e6b7b1e7-cc6d-4d34-9ab9-c8ec20dd85ce","videoID":"5fJl_ZX91l0","error":"YouTube did not show an English transcript."}"#
        let message = try JSONDecoder().decode(ChromeTranscriptMessage.self, from: Data(fixture.utf8))
        XCTAssertThrowsError(try message.makeTranscript(
            expectedRequestID: requestID,
            expectedVideoID: videoID,
            canonicalURL: videoURL
        )) { error in
            XCTAssertEqual(error as? ChromeTranscriptMessageError, .transcriptUnavailable("YouTube did not show an English transcript."))
        }
    }
}