import XCTest
@testable import CaptionGrabCore

final class TranscriptParsingTests: XCTestCase {
    func testParsesJSON3WithoutChangingCueBoundariesOrText() throws {
        let fixture = #"{"events":[{"tStartMs":3000,"dDurationMs":1500,"segs":[{"utf8":"A made-up"},{"utf8":" caption line."}]},{"tStartMs":4500,"dDurationMs":900,"segs":[{"utf8":"Second line\nkeeps its break."}]}]}"#
        let cues = try YouTubeTranscriptParser.parseJSON3(Data(fixture.utf8))
        XCTAssertEqual(cues, [
            TranscriptCue(startTimeMilliseconds: 3_000, text: "A made-up caption line."),
            TranscriptCue(startTimeMilliseconds: 4_500, text: "Second line\nkeeps its break.")
        ])
    }

    func testTimestampUsesHoursOnlyForLongVideos() {
        XCTAssertEqual(TranscriptCue(startTimeMilliseconds: 3_999, text: "x").displayTimestamp, "0:03")
        XCTAssertEqual(TranscriptCue(startTimeMilliseconds: 62_000, text: "x").displayTimestamp, "1:02")
        XCTAssertEqual(TranscriptCue(startTimeMilliseconds: 3_735_000, text: "x").displayTimestamp, "1:02:15")
    }

    func testExtractsTitleAndEnglishCaptionTracksFromSyntheticPlayerPage() throws {
        let html = #"<html><script>var ytInitialPlayerResponse = {"videoDetails":{"title":"Fictional & Sample"},"captions":{"playerCaptionsTracklistRenderer":{"captionTracks":[{"baseUrl":"https://www.youtube.com/api/timedtext?v=fixture","name":{"simpleText":"English"},"languageCode":"en"},{"baseUrl":"https://www.youtube.com/api/timedtext?v=fixture&kind=asr","name":{"simpleText":"English (auto-generated)"},"languageCode":"en","kind":"asr"}]}}};</script></html>"#
        let page = try YouTubePlayerPageParser.parse(html)
        XCTAssertEqual(page.title, "Fictional & Sample")
        XCTAssertEqual(page.captionTracks.count, 2)
        XCTAssertEqual(page.captionTracks[1].isAutoGenerated, true)
    }
}
