import XCTest
@testable import CaptionGrabCore

final class TranscriptExportTests: XCTestCase {
    private func sample() -> TranscriptData {
        TranscriptData(
            videoTitle: "Fictional & Sample",
            videoURL: URL(string: "https://www.youtube.com/watch?v=A1b2C3d4E5F")!,
            isAutoGenerated: false,
            cues: [
                TranscriptCue(startTimeMilliseconds: 3_000, text: "A made-up first line."),
                TranscriptCue(startTimeMilliseconds: 65_000, text: "A second synthetic line.\nWith a preserved break.")
            ]
        )
    }

    func testMarkdownUsesRequestedLayoutAndLeavesEachCueSeparate() {
        let markdown = TranscriptFormatter.markdown(for: sample())
        XCTAssertEqual(
            markdown,
            "**Fictional & Sample**\n\nYouTube Video url: https://www.youtube.com/watch?v=A1b2C3d4E5F\n\n0:03\nA made-up first line.\n\n1:05\nA second synthetic line.\nWith a preserved break."
        )
    }

    func testWordExportIsAValidZipWithEscapedDocumentText() throws {
        let data = try DocxExporter.makeDOCX(for: sample())
        XCTAssertEqual(Array(data.prefix(4)), [0x50, 0x4b, 0x03, 0x04])
        let bytes = String(decoding: data, as: UTF8.self)
        XCTAssertTrue(bytes.contains("Fictional &amp; Sample"))
        XCTAssertTrue(bytes.contains("A made-up first line."))
        XCTAssertTrue(bytes.contains("YouTube Video url:"))
        let temporaryURL = FileManager.default.temporaryDirectory.appendingPathComponent("CaptionGrab-\(UUID().uuidString).docx")
        defer { try? FileManager.default.removeItem(at: temporaryURL) }
        try data.write(to: temporaryURL)
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/unzip")
        process.arguments = ["-t", temporaryURL.path]
        let output = Pipe()
        process.standardOutput = output
        process.standardError = output
        try process.run()
        process.waitUntilExit()
        XCTAssertEqual(process.terminationStatus, 0, String(decoding: output.fileHandleForReading.readDataToEndOfFile(), as: UTF8.self))
    }
}
