import XCTest
@testable import CaptionGrabCore

final class TranscriptExportTests: XCTestCase {
    private func sample() -> TranscriptData {
        TranscriptData(
            videoTitle: "Fictional & Sample",
            videoURL: URL(string: "https://www.youtube.com/watch?v=A1b2C3d4E5F")!,
            isAutoGenerated: false,
            cues: [
                TranscriptCue(startTimeMilliseconds: 3_000, text: "A made-up first line."),
                TranscriptCue(startTimeMilliseconds: 65_000, text: "A second synthetic line.\nWith a preserved break.")
            ]
        )
    }

    func testMarkdownFileExportUsesHeadingClickableURLAndOneTimestampedLinePerCue() {
        let markdown = TranscriptFormatter.markdownFile(for: sample())
        XCTAssertEqual(
            markdown,
            "# Fictional & Sample\n\n**YouTube Video url:** [https://www.youtube.com/watch?v=A1b2C3d4E5F](<https://www.youtube.com/watch?v=A1b2C3d4E5F>)\n\n0:03 – A made-up first line.  \n1:05 – A second synthetic line.\nWith a preserved break."
        )
    }

    func testWordExportDeclaresModernCompatibilityAndDefaultFont() throws {
        let data = try DocxExporter.makeDOCX(for: sample())
        let settings = try unzipEntry("word/settings.xml", from: data)
        let styles = try unzipEntry("word/styles.xml", from: data)
        let relationships = try unzipEntry("word/_rels/document.xml.rels", from: data)
        let contentTypes = try unzipEntry("[Content_Types].xml", from: data)

        XCTAssertTrue(settings.contains("<w:compat><w:compatSetting w:name=\"compatibilityMode\" w:uri=\"http://schemas.microsoft.com/office/word\" w:val=\"15\"/></w:compat>"))
        XCTAssertTrue(styles.contains("<w:docDefaults><w:rPrDefault><w:rPr>"))
        XCTAssertTrue(styles.contains("w:ascii=\"Times New Roman\""))
        XCTAssertTrue(styles.contains("w:hAnsi=\"Times New Roman\""))
        XCTAssertTrue(styles.contains("<w:sz w:val=\"24\"/><w:szCs w:val=\"24\"/>"))
        XCTAssertTrue(styles.contains("<w:style w:type=\"paragraph\" w:default=\"1\" w:styleId=\"Normal\">"))
        XCTAssertTrue(relationships.contains("Id=\"rId3\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings\" Target=\"settings.xml\""))
        XCTAssertTrue(relationships.contains("Id=\"rId4\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles\" Target=\"styles.xml\""))
        XCTAssertTrue(contentTypes.contains("PartName=\"/word/settings.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml\""))
        XCTAssertTrue(contentTypes.contains("PartName=\"/word/styles.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml\""))
    }

    func testCopyAllMarkdownRemainsUnchanged() {
        XCTAssertEqual(
            TranscriptFormatter.markdown(for: sample()),
            "**Fictional & Sample**\n\nYouTube Video url: https://www.youtube.com/watch?v=A1b2C3d4E5F\n\n0:03\nA made-up first line.\n\n1:05\nA second synthetic line.\nWith a preserved break."
        )
    }

    func testWordExportMatchesRequestedFontsSizesHyperlinkAndCaptionParagraphs() throws {
        let data = try DocxExporter.makeDOCX(for: sample())
        XCTAssertEqual(Array(data.prefix(4)), [0x50, 0x4b, 0x03, 0x04])
        let document = try unzipEntry("word/document.xml", from: data)
        let relationships = try unzipEntry("word/_rels/document.xml.rels", from: data)
        XCTAssertTrue(document.contains("Fictional &amp; Sample"))
        XCTAssertTrue(document.contains("0:03 – A made-up first line."))
        XCTAssertTrue(document.contains("1:05 – A second synthetic line."))
        XCTAssertTrue(document.contains("<w:br/><w:t xml:space=\"preserve\">With a preserved break."))
        XCTAssertTrue(document.contains("YouTube Video url: "))
        XCTAssertTrue(document.contains("<w:hyperlink r:id=\"rId2\">"))
        XCTAssertTrue(document.contains("<w:color w:val=\"0563C1\"/>"))
        XCTAssertTrue(document.contains("<w:u w:val=\"single\"/>"))
        XCTAssertTrue(document.contains("<w:sz w:val=\"32\"/>"))
        XCTAssertEqual(document.components(separatedBy: "<w:sz w:val=\"24\"/>").count - 1, 4)
        XCTAssertEqual(document.components(separatedBy: "w:ascii=\"Times New Roman\"").count - 1, 5)
        XCTAssertEqual(document.components(separatedBy: "<w:p/>").count - 1, 2)
        XCTAssertEqual(document.components(separatedBy: "<w:p>").count - 1, 4)
        XCTAssertTrue(relationships.contains("Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink\""))
        XCTAssertTrue(relationships.contains("Target=\"https://www.youtube.com/watch?v=A1b2C3d4E5F\" TargetMode=\"External\""))

        let temporaryURL = FileManager.default.temporaryDirectory.appendingPathComponent("CaptionGrab-\(UUID().uuidString).docx")
        defer { try? FileManager.default.removeItem(at: temporaryURL) }
        try data.write(to: temporaryURL)
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/unzip")
        process.arguments = ["-t", temporaryURL.path]
        let output = Pipe()
        process.standardOutput = output
        process.standardError = output
        try process.run()
        process.waitUntilExit()
        XCTAssertEqual(process.terminationStatus, 0, String(decoding: output.fileHandleForReading.readDataToEndOfFile(), as: UTF8.self))
    }

    private func unzipEntry(_ name: String, from data: Data) throws -> String {
        let temporaryURL = FileManager.default.temporaryDirectory.appendingPathComponent("CaptionGrab-\(UUID().uuidString).docx")
        defer { try? FileManager.default.removeItem(at: temporaryURL) }
        try data.write(to: temporaryURL)
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/unzip")
        let entryPattern = name == "[Content_Types].xml" ? "[[]Content_Types].xml" : name
        process.arguments = ["-p", temporaryURL.path, entryPattern]
        let output = Pipe()
        process.standardOutput = output
        process.standardError = Pipe()
        try process.run()
        let contents = output.fileHandleForReading.readDataToEndOfFile()
        process.waitUntilExit()
        guard process.terminationStatus == 0 else {
            throw NSError(domain: "TranscriptExportTests", code: Int(process.terminationStatus))
        }
        return String(decoding: contents, as: UTF8.self)
    }
}
