#!/usr/bin/env python3
"""Exercise the CaptionGrab Chrome Native Messaging host with a synthetic fixture."""

from __future__ import annotations

import json
from pathlib import Path
import struct
import subprocess
import sys


def main() -> int:
    if len(sys.argv) != 2:
        raise SystemExit("usage: test-native-host.py PATH_TO_NATIVE_HOST")

    request_id = "e6b7b1e7-cc6d-4d34-9ab9-c8ec20dd85ce"
    message = {
        "type": "captiongrab.transcript",
        "requestID": request_id,
        "videoID": "5fJl_ZX91l0",
        "videoURL": "https://www.youtube.com/watch?v=5fJl_ZX91l0",
        "title": "Fictional native-host fixture",
        "captionLanguage": "English",
        "isAutoGenerated": None,
        "cues": [
            {"startTimeMilliseconds": 765000, "text": "Invented fixture caption."},
            {"startTimeMilliseconds": 771000, "text": "Second made-up cue."},
        ],
    }
    payload = json.dumps(message, separators=(",", ":")).encode("utf-8")
    native_origin = "chrome-extension://kajphiodjnkmgeidbcndikaaegghiffi/"
    completed = subprocess.run(
        [sys.argv[1], native_origin],
        input=struct.pack("<I", len(payload)) + payload,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if completed.returncode != 0:
        raise RuntimeError(f"Native host exited {completed.returncode}: {completed.stderr.decode(errors='replace')}")
    if len(completed.stdout) < 4:
        raise RuntimeError("Native host returned an incomplete response frame.")

    response_length = struct.unpack("<I", completed.stdout[:4])[0]
    response_bytes = completed.stdout[4:]
    if response_length != len(response_bytes):
        raise RuntimeError("Native host response frame length did not match its payload.")
    response = json.loads(response_bytes)
    if response != {"ok": True, "requestID": request_id}:
        raise RuntimeError(f"Native host returned an unexpected acknowledgement: {response!r}")

    inbox = (
        Path.home()
        / "Library"
        / "Application Support"
        / "CaptionGrab"
        / "ChromeInbox"
    )
    inbox_existed = inbox.exists()
    support_existed = inbox.parent.exists()
    result_file = inbox / f"{request_id}.json"
    try:
        stored_message = json.loads(result_file.read_bytes())
        if stored_message != message:
            raise RuntimeError("Native host did not persist the expected synthetic transcript.")
    finally:
        result_file.unlink(missing_ok=True)
        if not inbox_existed:
            try:
                inbox.rmdir()
            except OSError:
                pass
        if not support_existed:
            try:
                inbox.parent.rmdir()
            except OSError:
                pass
    print("Native Messaging host frame, origin, validation, and local inbox test passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
