import Foundation

public enum CaptionTrackSelector {
    public static func englishTrack(from tracks: [CaptionTrack]) -> CaptionTrack? {
        let english = tracks.filter { track in
            let code = track.languageCode.lowercased()
            return code == "en" || code.hasPrefix("en-")
        }
        guard !english.isEmpty else { return nil }

        return english.first(where: { !$0.isAutoGenerated && $0.languageCode.lowercased() == "en" })
            ?? english.first(where: { !$0.isAutoGenerated })
            ?? english.first(where: { $0.languageCode.lowercased() == "en" })
            ?? english.first
    }
}
