import Foundation

public enum ChromeTranscriptMessageError: Error, Equatable, LocalizedError, Sendable {
    case transcriptUnavailable(String)
    case invalidMessage(String)

    public var errorDescription: String? {
        switch self {
        case .transcriptUnavailable(let message): message
        case .invalidMessage(let message): message
        }
    }
}

public struct ChromeTranscriptMessage: Codable, Equatable, Sendable {
    public let type: String
    public let requestID: String
    public let videoID: String
    public let videoURL: String?
    public let title: String?
    public let captionLanguage: String?
    public let isAutoGenerated: Bool?
    public let cues: [TranscriptCue]?
    public let error: String?

    public func makeTranscript(
        expectedRequestID: String,
        expectedVideoID: String,
        canonicalURL: URL
    ) throws -> TranscriptData {
        guard let requestUUID = UUID(uuidString: requestID),
              let expectedUUID = UUID(uuidString: expectedRequestID),
              requestUUID == expectedUUID,
              isValidVideoID(videoID),
              videoID == expectedVideoID,
              isValidWatchURL(canonicalURL.absoluteString, matching: videoID)
        else {
            throw ChromeTranscriptMessageError.invalidMessage("The Chrome response did not match the video requested in CaptionGrab.")
        }

        if type == "captiongrab.error" {
            let message = String((error ?? "Chrome could not read the transcript.").prefix(1_000))
            throw ChromeTranscriptMessageError.transcriptUnavailable(message)
        }
        guard type == "captiongrab.transcript",
              isValidWatchURL(videoURL, matching: videoID) else {
            throw ChromeTranscriptMessageError.invalidMessage("Chrome returned an unsupported or mismatched response.")
        }
        guard let language = captionLanguage?.trimmingCharacters(in: .whitespacesAndNewlines).lowercased(),
              language == "english" || language == "en" else {
            throw ChromeTranscriptMessageError.invalidMessage("Chrome did not confirm that the transcript is English.")
        }
        guard let title = title?.trimmingCharacters(in: .whitespacesAndNewlines),
              !title.isEmpty, title.count <= 500,
              let cues, !cues.isEmpty, cues.count <= 100_000 else {
            throw ChromeTranscriptMessageError.invalidMessage("Chrome returned an empty or invalid transcript.")
        }
        let totalCaptionCharacters = cues.reduce(0) { partial, cue in
            partial.addingReportingOverflow(cue.text.utf8.count).overflow ? Int.max : partial + cue.text.utf8.count
        }
        guard totalCaptionCharacters <= 10_000_000,
              cues.allSatisfy({ $0.startTimeMilliseconds >= 0 && !$0.text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty }) else {
            throw ChromeTranscriptMessageError.invalidMessage("Chrome returned invalid caption segments.")
        }

        return TranscriptData(
            videoTitle: title,
            videoURL: canonicalURL,
            isAutoGenerated: isAutoGenerated,
            cues: cues
        )
    }

    private func isValidVideoID(_ value: String) -> Bool {
        value.count == 11 && value.unicodeScalars.allSatisfy {
            CharacterSet(charactersIn: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-").contains($0)
        }
    }

    private func isValidWatchURL(_ value: String?, matching videoID: String) -> Bool {
        guard let value, let components = URLComponents(string: value),
              components.scheme?.lowercased() == "https",
              components.host?.lowercased() == "www.youtube.com",
              components.path == "/watch",
              components.queryItems?.first(where: { $0.name == "v" })?.value == videoID,
              components.user == nil, components.password == nil, components.port == nil else { return false }
        return true
    }
}
