import Foundation

public enum CaptionGrabError: Error, Equatable, LocalizedError, Sendable {
    case invalidLink
    case noEnglishCaptions
    case videoUnavailable
    case requestBlocked
    case offline
    case youtubeChanged
    case exportFailed

    public var errorDescription: String? {
        switch self {
        case .invalidLink:
            return "That doesn't look like a supported YouTube video link."
        case .noEnglishCaptions:
            return "CaptionGrab couldn't read English captions directly. If the transcript is visible in Chrome, set up the Chrome extension to capture it."
        case .videoUnavailable:
            return "This video is private, age-restricted, or unavailable to CaptionGrab."
        case .requestBlocked:
            return "YouTube temporarily blocked this request. Try again later."
        case .offline:
            return "CaptionGrab can't reach YouTube. Check your internet connection and try again."
        case .youtubeChanged:
            return "YouTube's page or caption format changed, so CaptionGrab couldn't read this video."
        case .exportFailed:
            return "CaptionGrab couldn't save the selected file. Check the folder's permissions and try again."
        }
    }
}

public struct YouTubeLink: Equatable, Sendable {
    public let videoID: String
    public let canonicalURL: URL

    public init(videoID: String, canonicalURL: URL) {
        self.videoID = videoID
        self.canonicalURL = canonicalURL
    }

    public static func parse(_ input: String) throws -> YouTubeLink {
        try YouTubeLinkParser.parse(input)
    }
}

public struct CaptionTrack: Equatable, Sendable {
    public let languageCode: String
    public let languageName: String
    public let isAutoGenerated: Bool
    public let captionURL: URL

    public init(languageCode: String, languageName: String, isAutoGenerated: Bool, captionURL: URL) {
        self.languageCode = languageCode
        self.languageName = languageName
        self.isAutoGenerated = isAutoGenerated
        self.captionURL = captionURL
    }
}

public struct PlayerPage: Equatable, Sendable {
    public let title: String
    public let captionTracks: [CaptionTrack]

    public init(title: String, captionTracks: [CaptionTrack]) {
        self.title = title
        self.captionTracks = captionTracks
    }
}

public struct TranscriptCue: Codable, Equatable, Sendable {
    public let startTimeMilliseconds: Int
    public let text: String

    public init(startTimeMilliseconds: Int, text: String) {
        self.startTimeMilliseconds = startTimeMilliseconds
        self.text = text
    }

    public var displayTimestamp: String {
        let seconds = max(0, startTimeMilliseconds) / 1_000
        let hours = seconds / 3_600
        let minutes = (seconds % 3_600) / 60
        let remainingSeconds = seconds % 60
        if hours > 0 {
            return String(format: "%d:%02d:%02d", hours, minutes, remainingSeconds)
        }
        return String(format: "%d:%02d", seconds / 60, remainingSeconds)
    }
}

public struct TranscriptData: Equatable, Sendable {
    public let videoTitle: String
    public let videoURL: URL
    public let isAutoGenerated: Bool?
    public let recoveredWithOnDeviceAI: Bool
    public let cues: [TranscriptCue]

    public init(videoTitle: String, videoURL: URL, isAutoGenerated: Bool?, cues: [TranscriptCue], recoveredWithOnDeviceAI: Bool = false) {
        self.videoTitle = videoTitle
        self.videoURL = videoURL
        self.isAutoGenerated = isAutoGenerated
        self.recoveredWithOnDeviceAI = recoveredWithOnDeviceAI
        self.cues = cues
    }
}

public struct RecentVideo: Codable, Equatable, Identifiable, Sendable {
    public var id: String { videoID }
    public let videoID: String
    public let title: String
    public let videoURL: URL
    public let lastFetchedAt: Date

    public init(videoID: String, title: String, videoURL: URL, lastFetchedAt: Date = Date()) {
        self.videoID = videoID
        self.title = title
        self.videoURL = videoURL
        self.lastFetchedAt = lastFetchedAt
    }
}
