import Foundation

public struct YouTubeTranscriptClient: Sendable {
    private static let session: URLSession = {
        let configuration = URLSessionConfiguration.ephemeral
        configuration.httpCookieStorage = nil
        configuration.httpCookieAcceptPolicy = .never
        configuration.urlCache = nil
        configuration.requestCachePolicy = .reloadIgnoringLocalCacheData
        configuration.httpShouldSetCookies = false
        return URLSession(configuration: configuration, delegate: YouTubeRedirectPolicy(), delegateQueue: nil)
    }()

    public init() {}

    public func fetch(link: YouTubeLink) async throws -> TranscriptData {
        do {
            var pageComponents = URLComponents(string: "https://www.youtube.com/watch")!
            pageComponents.queryItems = [
                URLQueryItem(name: "v", value: link.videoID),
                URLQueryItem(name: "hl", value: "en")
            ]
            var pageRequest = URLRequest(url: pageComponents.url!, cachePolicy: .reloadIgnoringLocalCacheData, timeoutInterval: 25)
            pageRequest.setValue("text/html,application/xhtml+xml", forHTTPHeaderField: "Accept")
            pageRequest.setValue("en-US,en;q=0.9", forHTTPHeaderField: "Accept-Language")
            let (pageData, pageResponse) = try await Self.session.data(for: pageRequest)
            try Self.validateResponse(pageResponse)
            guard let html = String(data: pageData, encoding: .utf8) else { throw CaptionGrabError.youtubeChanged }

            let page = try YouTubePlayerPageParser.parse(html)
            guard let track = CaptionTrackSelector.englishTrack(from: page.captionTracks) else {
                throw CaptionGrabError.noEnglishCaptions
            }
            let captionURL = try Self.json3URL(for: track.captionURL)
            var captionRequest = URLRequest(url: captionURL, cachePolicy: .reloadIgnoringLocalCacheData, timeoutInterval: 25)
            captionRequest.setValue("application/json,text/plain,*/*", forHTTPHeaderField: "Accept")
            captionRequest.setValue("https://www.youtube.com/", forHTTPHeaderField: "Referer")
            let (captionData, captionResponse) = try await Self.session.data(for: captionRequest)
            try Self.validateResponse(captionResponse)
            let cues = try YouTubeTranscriptParser.parse(captionData)
            return TranscriptData(
                videoTitle: page.title,
                videoURL: link.canonicalURL,
                isAutoGenerated: track.isAutoGenerated,
                cues: cues
            )
        } catch let error as CaptionGrabError {
            throw error
        } catch let error as URLError {
            switch error.code {
            case .notConnectedToInternet, .networkConnectionLost, .cannotConnectToHost, .cannotFindHost, .timedOut:
                throw CaptionGrabError.offline
            default:
                throw CaptionGrabError.youtubeChanged
            }
        } catch {
            throw CaptionGrabError.youtubeChanged
        }
    }

    private static func validateResponse(_ response: URLResponse) throws {
        guard let http = response as? HTTPURLResponse else { throw CaptionGrabError.youtubeChanged }
        switch http.statusCode {
        case 200..<300:
            return
        case 429:
            throw CaptionGrabError.requestBlocked
        case 401, 403, 404, 410:
            throw CaptionGrabError.videoUnavailable
        default:
            throw CaptionGrabError.youtubeChanged
        }
    }

    private static func json3URL(for source: URL) throws -> URL {
        guard source.scheme?.lowercased() == "https",
              let host = source.host?.lowercased(),
              host == "youtube.com" || host.hasSuffix(".youtube.com"),
              var components = URLComponents(url: source, resolvingAgainstBaseURL: false)
        else { throw CaptionGrabError.youtubeChanged }
        var items = components.queryItems ?? []
        items.removeAll { $0.name == "fmt" }
        items.append(URLQueryItem(name: "fmt", value: "json3"))
        components.queryItems = items
        guard let url = components.url else { throw CaptionGrabError.youtubeChanged }
        return url
    }
}

private final class YouTubeRedirectPolicy: NSObject, URLSessionTaskDelegate, @unchecked Sendable {
    func urlSession(_ session: URLSession, task: URLSessionTask, willPerformHTTPRedirection response: HTTPURLResponse, newRequest request: URLRequest, completionHandler: @escaping (URLRequest?) -> Void) {
        guard let url = request.url,
              url.scheme?.lowercased() == "https",
              let host = url.host?.lowercased(),
              host == "youtube.com" || host.hasSuffix(".youtube.com")
        else {
            completionHandler(nil)
            return
        }
        completionHandler(request)
    }
}
