import Foundation

public enum YouTubePlayerPageParser {
    public static func parse(_ html: String) throws -> PlayerPage {
        var searchStart = html.startIndex
        while searchStart < html.endIndex,
              let keyRange = html.range(of: "ytInitialPlayerResponse", range: searchStart..<html.endIndex),
              let brace = html[keyRange.upperBound..<html.endIndex].firstIndex(of: "{") {
            if let json = extractObject(in: html, startingAt: brace),
               let data = json.data(using: .utf8),
               let response = try? JSONSerialization.jsonObject(with: data) as? [String: Any] {
                if let status = (response["playabilityStatus"] as? [String: Any])?["status"] as? String,
                   status != "OK" {
                    throw CaptionGrabError.videoUnavailable
                }
                if let title = title(from: response), !title.isEmpty {
                    return PlayerPage(title: title, captionTracks: tracks(from: response))
                }
            }
            searchStart = html.index(after: brace)
        }
        throw CaptionGrabError.youtubeChanged
    }

    private static func title(from response: [String: Any]) -> String? {
        if let details = response["videoDetails"] as? [String: Any],
           let title = details["title"] as? String {
            return title
        }
        let microformat = response["microformat"] as? [String: Any]
        let renderer = microformat?["playerMicroformatRenderer"] as? [String: Any]
        let title = renderer?["title"] as? [String: Any]
        if let simple = title?["simpleText"] as? String { return simple }
        if let runs = title?["runs"] as? [[String: Any]] {
            return runs.compactMap { $0["text"] as? String }.joined()
        }
        return nil
    }

    private static func tracks(from response: [String: Any]) -> [CaptionTrack] {
        guard let captions = response["captions"] as? [String: Any],
              let renderer = captions["playerCaptionsTracklistRenderer"] as? [String: Any],
              let items = renderer["captionTracks"] as? [[String: Any]] else { return [] }

        return items.compactMap { item in
            guard let code = item["languageCode"] as? String,
                  let baseURL = item["baseUrl"] as? String,
                  let url = URL(string: baseURL),
                  url.scheme?.lowercased() == "https",
                  let host = url.host?.lowercased(),
                  host == "youtube.com" || host.hasSuffix(".youtube.com")
            else { return nil }

            let nameData = item["name"] as? [String: Any]
            let name = nameData?["simpleText"] as? String
                ?? (nameData?["runs"] as? [[String: Any]])?.compactMap { $0["text"] as? String }.joined()
                ?? code
            return CaptionTrack(
                languageCode: code,
                languageName: name,
                isAutoGenerated: (item["kind"] as? String) == "asr",
                captionURL: url
            )
        }
    }

    private static func extractObject(in text: String, startingAt start: String.Index) -> String? {
        var depth = 0
        var insideString = false
        var escaped = false
        var index = start

        while index < text.endIndex {
            let character = text[index]
            if insideString {
                if escaped {
                    escaped = false
                } else if character == "\\" {
                    escaped = true
                } else if character == "\"" {
                    insideString = false
                }
            } else if character == "\"" {
                insideString = true
            } else if character == "{" {
                depth += 1
            } else if character == "}" {
                depth -= 1
                if depth == 0 {
                    return String(text[start...index])
                }
            }
            index = text.index(after: index)
        }
        return nil
    }
}
